#Dockerfile
FROM debian

RUN apt-get update -y
RUN apt-get install -y python3 python3-pip git

RUN mkdir /code

RUN git clone https://github.com/garciarodriguezenrique/AppTurismo
RUN mv AppTurismo /code

RUN pip3 install django 
RUN pip3 install django-rest-framework 

RUN python3 -m pip install django-cors-headers
RUN python3 -m pip install requests
RUN python3 -m pip install geocoder
RUN python3 -m pip install pandas
RUN python3 -m pip install pybase64
RUN python3 -m pip install pillow

ARG APPDIR=/code/AppTurismo/django-projects/TourismApp/

WORKDIR $APPDIR

EXPOSE 8005
ENTRYPOINT ["python3", "manage.py"]
CMD ["runserver", "0.0.0.0:8005"]

