# Generated by Django 2.1.3 on 2018-12-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PointOfInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('venue_id', models.CharField(blank=True, default='', max_length=100)),
                ('venue_name', models.CharField(blank=True, default='', max_length=100)),
                ('coordinates', models.CharField(blank=True, default='', max_length=250)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
