# Generated by Django 2.1.3 on 2018-12-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('externalapis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointofinterest',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='pointofinterest',
            name='lat',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='pointofinterest',
            name='lng',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
