# Generated by Django 2.1.3 on 2018-12-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('externalapis', '0002_auto_20181203_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointofinterest',
            name='lat',
            field=models.DecimalField(decimal_places=10, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='pointofinterest',
            name='lng',
            field=models.DecimalField(decimal_places=10, max_digits=19, null=True),
        ),
    ]
