# Generated by Django 2.1.4 on 2018-12-05 18:10

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('externalapis', '0004_auto_20181205_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointofinterest',
            name='category',
            field=django_mysql.models.ListCharField(models.CharField(max_length=20), max_length=273, size=13),
        ),
    ]
