# Generated by Django 2.1.4 on 2018-12-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('externalapis', '0005_auto_20181205_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointofinterest',
            name='rating',
        ),
        migrations.AddField(
            model_name='pointofinterest',
            name='reference',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
