# Generated by Django 2.1.4 on 2018-12-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('externalapis', '0006_auto_20181206_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointofinterest',
            name='rating',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
    ]
