# Generated by Django 2.1.4 on 2018-12-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('externalapis', '0007_pointofinterest_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointofinterest',
            name='rating',
            field=models.DecimalField(decimal_places=4, max_digits=4, null=True),
        ),
    ]
