# Generated by Django 2.1.4 on 2018-12-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('externalapis', '0008_auto_20181207_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointofinterest',
            name='rating',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
