# Generated by Django 2.1.5 on 2019-01-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('externalapis', '0009_auto_20181207_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointofinterest',
            name='formatted_address',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
