# Generated by Django 2.1.1 on 2018-10-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercontent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='venue',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='image',
            name='venue',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
