# Generated by Django 2.1.1 on 2018-10-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercontent', '0002_auto_20181005_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='venue',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='image',
            name='venue',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
