# Generated by Django 2.1.4 on 2018-12-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercontent', '0004_auto_20181214_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='owner',
        ),
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(max_length=254, upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
