# Generated by Django 2.1.4 on 2019-01-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercontent', '0005_auto_20181214_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('avg_rating', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('review_number', models.IntegerField()),
                ('venue_id', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
